train_file: ["/home/scis_user/datasets/roco-dataset/train.json",
             "/home/scis_user/datasets/image_clef_train.json",
            "/home/scis_user/datasets/release/medcat.json"]


# train_file: ["/home/scis_user/datasets/coco_train.json",
#              "/home/scis_user/datasets/coco_val.json"]
# each train_file (json) contains a python list where each item is {'image': img_path, 'caption': text or list_of_text }               
bert_config: 'configs/config_bert.json'

image_res: 224
vision_width: 768
embed_dim: 256
batch_size: 256
temp: 0.07
mlm_probability: 0.15
queue_size: 65536
momentum: 0.995
alpha: 0.4

optimizer: {opt: adamW, lr: 1e-4, weight_decay: 0.05}
schedular: {sched: cosine, lr: 1e-4, epochs: 30, min_lr: 1e-5, decay_rate: 0.9, warmup_lr: 1e-5, warmup_epochs: 10, cooldown_epochs: 0}


